services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        container_name: php
        networks:
            - laravel-network

    mysql:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=password
        volumes:
            - ./storage/mysql:/var/lib/mysql
        container_name: mysql
        networks:
            - laravel-network
        command: ["mysqld", "--init-file=/docker-entrypoint-initdb.d/init.sql"]

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
            - node
        container_name: nginx
        networks:
            - laravel-network
        environment:
            VITE_URL: "http://localhost:5173"

    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules
        working_dir: /var/www/html
        command: ["npm", "run", "dev"]
        container_name: node
        depends_on:
            - php
        networks:
            - laravel-network
        ports:
            - "5173:5173"
        environment:
            VITE_APP_URL: "http://localhost"

networks:
    laravel-network:
        driver: bridge
